#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using Brisk.Config;
using Brisk.Entities;
using Brisk.Serialization;
using UnityEditor;
using UnityEngine;

namespace Brisk.Actions
{
    public static class ActionGenerator
    {
        [MenuItem("Brisk/Generate Action Set", false, 4)]
        public static void GenerateClasses()
        {
            var types = AppDomain.CurrentDomain.GetAssemblies()
                .SelectMany(a => a.GetTypes())
                .Where(t => t.IsClass && t.IsSubclassOf(typeof(NetBehaviour)));


            var actions = new Dictionary<Type, List<Tuple<MethodInfo, int, bool>>>();
            var actionList = new List<string>();
            foreach (var type in types)
            {
                foreach (var method in type.GetMethods())
                {
                    var attribute = (Action)Attribute.GetCustomAttribute(method, typeof(Action));
                    if (attribute == null) continue;
                    if (!actions.ContainsKey(type)) actions.Add(type, new List<Tuple<MethodInfo, int, bool>>());
                    actions[type].Add(Tuple.Create(method, actionList.Count, attribute.Self));

                    actionList.Add($"{type.FullName}.{method.Name}");
                }
            }
            
            
            var result = new StringBuilder();
            result.AppendLine("// #### AUTO-GENERATED CODE ####");
            result.AppendLine("// Please avoid editing");
            result.AppendLine("// Copyright © Brisk Technologies");
            result.AppendLine("");
            result.AppendLine("namespace Brisk.Actions {");
            result.AppendLine("    public sealed class AutoGenerated_BriskActionSet : Brisk.Actions.ActionSet {");

            AddActions(result, actions);
            
            result.AppendLine("    }");
            result.AppendLine("    public static class AutoGenerated_BriskActionExtensions {");

            AddExtensions(result, actions);
            
            result.AppendLine("    }");
            result.AppendLine("}");
            
            File.WriteAllText("Assets/Resources/AutoGenerated_BriskActionSet.cs", result.ToString());
            AssetDatabase.Refresh();
        }

        [MenuItem("Brisk/Save Action Set", false, 5)]
        public static void SaveSerialization()
        {
            var scriptableObject = (ActionSet)ScriptableObject.CreateInstance("AutoGenerated_BriskActionSet");
            if (scriptableObject == null) return;
            AssetDatabase.CreateAsset(scriptableObject, "Assets/Resources/AutoGenerated_BriskActionSet.asset");
            foreach (var config in Resources.FindObjectsOfTypeAll<ServerConfig>())
                config.ActionSet = scriptableObject;
        }

        private static void AddExtensions(StringBuilder result, Dictionary<Type, List<Tuple<MethodInfo, int, bool>>> actions)
        {
            foreach (var actionSet in actions)
            foreach (var (method, index, self) in actionSet.Value)
            {
                var inArgs = new StringBuilder();
                var callArgs = new StringBuilder();
                var actionArgs = new StringBuilder();
                var i = 0;

                foreach (var parameter in method.GetParameters())
                {
                    inArgs.Append(", ");
                    inArgs.Append(parameter.ParameterType.FullName);
                    inArgs.Append(" arg");
                    inArgs.Append(i);
                    
                    if(i > 0) callArgs.Append(",");
                    callArgs.Append("arg");
                    callArgs.Append(i);
                    
                    actionArgs.Append(",");
                    actionArgs.Append("arg");
                    actionArgs.Append(i);

                    i++;
                }
                
                result.AppendLine($"        public static void Net_{method.Name}(this {actionSet.Key.FullName} bhr{inArgs}) {{");
                if(self)result.AppendLine($"            bhr.{method.Name}({callArgs});");
                result.AppendLine($"            bhr.Entity.Peer.Messages.ActionLocal({index}, bhr.Entity.Entity.Id, bhr.Entity.Entity.Behaviour(bhr){actionArgs});");
                result.AppendLine( "        }");
            }
        }

        private static void AddActions(StringBuilder result, Dictionary<Type, List<Tuple<MethodInfo, int, bool>>> actions)
        {
            result.AppendLine( "        private readonly System.Collections.Generic.Dictionary<int, System.Action<Brisk.Entities.NetBehaviour, Lidgren.Network.NetIncomingMessage>> actions =");
            result.AppendLine( "            new System.Collections.Generic.Dictionary<int, System.Action<Brisk.Entities.NetBehaviour, Lidgren.Network.NetIncomingMessage>> {");

            foreach (var actionSet in actions)
            foreach (var (method, index, self) in actionSet.Value)
            {
                result.AppendLine($"                {{{index}, (bhr, msg) => {{");
                AddParameters(result, actionSet.Key.FullName, method);
                result.AppendLine($"                }}}},");
            }
            result.AppendLine( "        };");
            result.AppendLine( "");
            result.AppendLine( "        public override void Call(Brisk.Entities.NetEntity entity, byte behaviourId, Lidgren.Network.NetIncomingMessage msg, int actionId) {");
            result.AppendLine( "            if (actions.TryGetValue(actionId, out var action)) action(entity.Behaviour(behaviourId), msg);");
            result.AppendLine(@"            else UnityEngine.Debug.LogError($""Action not found with ID: {actionId}"");");
            result.AppendLine( "        }");
        }

        private static void AddParameters(StringBuilder result, string fullName, MethodInfo method)
        {
            var i = 0;
            var args = new StringBuilder();
            foreach (var parameter in method.GetParameters())
            {
                result.AppendLine($"                    var arg{++i} = {SerializerGenerator.ReadMessageData(parameter.ParameterType.FullName)};");
                if (args.Length > 0) args.Append(",");
                args.Append("arg");
                args.Append(i);
            }
            result.AppendLine($"                    (({fullName})bhr).{method.Name}({args});");
        }
    }
}
#endif
